---
apiVersion: v1
kind: ReplicationController
metadata:
  app: httpd-rc
  labels:
    author: tjean
spec:
  replicas: 3
  selector:
    app: httpd-rc
  template:
    metadata:
      name: httpd-pod 
      labels:
        app: myapp
    spec:
      containers:
        - name: myhttpd
          image: httpd
          ports:
            - containerPort: 80
              hostPort: 8080
...              
